
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DigiGuard
{

using System;
    using System.Collections.Generic;
    
public partial class Change
{

    public int Id { get; set; }

    public string UserName { get; set; }

    public Nullable<int> ReportID { get; set; }

    public string Data { get; set; }

    public Nullable<System.DateTime> Time { get; set; }



    public virtual FactReport FactReport { get; set; }

    public virtual DimUser DimUser { get; set; }

}

}
